USE [BDN]
GO

/****** Object:  StoredProcedure [dbo].[D_DATA_PROCEDURE]    Script Date: 14/10/2021 08:57:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<RAFAEL_BARBOSA>
-- Create date: <2021-05-19>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[D_DATA_PROCEDURE]

AS
BEGIN

IF (OBJECT_ID('tempdb.dbo.#TEMP_DIM_DATA') IS NOT NULL )  BEGIN DROP TABLE #TEMP_DIM_DATA	END;
IF (OBJECT_ID('tempdb.dbo.#TEMP_DIM_DATA_1') IS NOT NULL) BEGIN DROP TABLE #TEMP_DIM_DATA_1 END;
IF (OBJECT_ID('tempdb.dbo.#TEMP_DIM_DATA_2') IS NOT NULL) BEGIN DROP TABLE #TEMP_DIM_DATA_2 END;


;WITH DATES ([DATE]) AS(
SELECT CONVERT(DATE,'1900-01-01') AS [DATE]
UNION ALL
SELECT DATEADD(DAY, 1, [DATE])
FROM DATES
WHERE [DATE] < '1988-12-31')


SELECT *
,IIF(V1.ANO_BISSEXTO = 'S',V1.DIA_ANO, IIF(V1.DIA_ANO <= 59,V1.DIA_ANO,V1.DIA_ANO+1)) AS DIA_ANO_AJUSTADO

INTO #TEMP_DIM_DATA_1

FROM (
SELECT
 CAST(CONVERT(CHAR(8), [DATE], 112) AS INT) AS SKDATA
,NULL AS EVENTO
,NULL AS ESTACAO
,[DATE] AS [DATA]
,[DATE] AS DATA2
,YEAR([DATE]) AS ANO
,MONTH([DATE]) AS MES
,DAY([DATE]) AS DIA
,CONCAT(DAY([DATE]),'/', MONTH([DATE])) AS DIA_MES
,UPPER(FORMAT ([DATE], 'MMMM', 'pt-BR' ))  AS NOME_MES
,DATEPART(DY , [DATE]) AS DIA_ANO
,CONVERT(CHAR(6), [DATE], 112) AS ANO_MES
,DATEPART(DW, [DATE]) AS NUMERO_DIA_SEMANA
,UPPER(FORMAT ([DATE], 'MMM', 'pt-BR' ))  AS NOME_MES_ABREV
,IIF(YEAR([DATE]) % 4 <> 0,'N', IIF(YEAR([DATE]) % 100 <> 0, 'S', IIF (YEAR([DATE]) % 400 <> 0,'N','S'))) AS ANO_BISSEXTO
,CASE WHEN DATEPART(DW, [DATE])  IN (1,7) THEN 'S'ELSE'N'END AS FINAL_SEMANA
,CONCAT(UPPER(FORMAT ([DATE], 'MMM', 'pt-BR' )),'/', YEAR([DATE])) AS NOME_ANO_MES
,CASE WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') IN (0101,2104 ,0105 ,0709 ,1210 ,0211 ,1511 ,2512)  THEN 'S'ELSE 'N'END AS FERIADO
,CASE WHEN DATEPART(DW, [DATE]) IN (1,7) OR REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') IN (0101,2104 ,0105 ,0709 ,1210 ,0211 ,1511 ,2512) THEN 'N' ELSE'S'END AS DIA_UTIL
,CASE WHEN DATENAME(MM,[DATE]) IN ('January', 'February','March','April', 'May','June')THEN 1 WHEN DATENAME(MM,[DATE]) IN ('July', 'August','September','October', 'November', 'December') THEN 2 END AS SEMESTRE
,CASE DATENAME(DW, [DATE]) WHEN 'Monday'THEN 'SEGUNDA'WHEN 'Tuesday'THEN 'TERÇA'WHEN 'Wednesday'THEN 'QUARTA'WHEN 'Thursday'THEN 'QUINTA'WHEN 'Friday'THEN 'SEXTA'WHEN 'Saturday'THEN 'SÁBADO'WHEN 'Sunday'THEN 'DOMINGO'END AS DIA_SEMANA
,CASE WHEN DATENAME(MM,[DATE]) IN ('January', 'February','March') THEN 1 WHEN DATENAME(MM,[DATE]) IN ('April', 'May','June') THEN 2 WHEN DATENAME(MM,[DATE]) IN ('July', 'August','September') THEN 3 WHEN DATENAME(MM,[DATE]) IN ('October', 'November', 'December') THEN 4 END AS TRIMESTRE
,CASE WHEN DATENAME(MM,[DATE]) IN ('January', 'February') THEN 1 WHEN DATENAME(MM,[DATE]) IN ('March', 'April') THEN 2 WHEN DATENAME(MM,[DATE]) IN ('May','June') THEN 3 WHEN DATENAME(MM,[DATE]) IN ('July', 'August') THEN 4 WHEN DATENAME(MM,[DATE]) IN ('September', 'October') THEN 5 WHEN DATENAME(MM,[DATE]) IN ('November', 'December') THEN 6 END AS BIMESTRE
,CASE WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0101  THEN 'CONFRATERNIZAÇÃO UNIVERSAL' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 2104  THEN 'TIRADENTES' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0105  THEN  'DIA DO TRABALHO' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0709  THEN 'INDEPÊNCIA DO BRASIL' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 1210  THEN  'NOSSA SENHORA APARECIDA' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0211  THEN  'FINADOS' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 1511  THEN 'PROCLAMAÇÃO DA REPÚBLICA' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 2512 THEN 'NATAL' ELSE  NULL END AS NOME_FERIADO
,FORMAT(CAST(DATEADD(DAY, -1*(DATEPART(WEEKDAY, [DATE])-2), [DATE]) AS DATE), 'dd/MM', 'pt-BR' )+' a '+FORMAT(DATEADD(DAY,7,CAST(DATEADD(DAY, -1*(DATEPART(WEEKDAY, [DATE])-2), [DATE]) AS DATE)), 'dd/MM', 'pt-BR') AS SEMANA_DE_ATE


FROM DATES

) AS V1

OPTION (MAXRECURSION 32767) 



;WITH DATES_2 ([DATE]) AS(
SELECT CONVERT(DATE,'1989-01-01') AS [DATE]
UNION ALL
SELECT DATEADD(DAY, 1, [DATE])
FROM DATES_2
WHERE [DATE] < '2077-12-31')



SELECT *
,IIF(V1.ANO_BISSEXTO = 'S',V1.DIA_ANO, IIF(V1.DIA_ANO <= 59,V1.DIA_ANO,V1.DIA_ANO+1)) AS DIA_ANO_AJUSTADO
INTO #TEMP_DIM_DATA_2
FROM (
SELECT
 CAST(CONVERT(CHAR(8), [DATE], 112) AS INT) AS SKDATA
,NULL AS EVENTO
,NULL AS ESTACAO
,[DATE] AS [DATA]
,[DATE] AS DATA2
,YEAR([DATE]) AS ANO
,MONTH([DATE]) AS MES
,DAY([DATE]) AS DIA
,CONCAT(DAY([DATE]),'/', MONTH([DATE])) AS DIA_MES
,UPPER(FORMAT ([DATE], 'MMMM', 'pt-BR' ))  AS NOME_MES
,DATEPART(DY , [DATE]) AS DIA_ANO
,CONVERT(CHAR(6), [DATE], 112) AS ANO_MES
,DATEPART(DW, [DATE]) AS NUMERO_DIA_SEMANA
,UPPER(FORMAT ([DATE], 'MMM', 'pt-BR' ))  AS NOME_MES_ABREV
,IIF(YEAR([DATE]) % 4 <> 0,'N', IIF(YEAR([DATE]) % 100 <> 0, 'S', IIF (YEAR([DATE]) % 400 <> 0,'N','S'))) AS ANO_BISSEXTO
,CASE WHEN DATEPART(DW, [DATE])  IN (1,7) THEN 'S'ELSE'N'END AS FINAL_SEMANA
,CONCAT(UPPER(FORMAT ([DATE], 'MMM', 'pt-BR' )),'/', YEAR([DATE])) AS NOME_ANO_MES
,CASE WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') IN (0101,2104 ,0105 ,0709 ,1210 ,0211 ,1511 ,2512)  THEN 'S'ELSE 'N'END AS FERIADO
,CASE WHEN DATEPART(DW, [DATE]) IN (1,7) OR REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') IN (0101,2104 ,0105 ,0709 ,1210 ,0211 ,1511 ,2512) THEN 'N' ELSE'S'END AS DIA_UTIL
,CASE WHEN DATENAME(MM,[DATE]) IN ('January', 'February','March','April', 'May','June')THEN 1 WHEN DATENAME(MM,[DATE]) IN ('July', 'August','September','October', 'November', 'December') THEN 2 END AS SEMESTRE
,CASE DATENAME(DW, [DATE]) WHEN 'Monday'THEN 'SEGUNDA'WHEN 'Tuesday'THEN 'TERÇA'WHEN 'Wednesday'THEN 'QUARTA'WHEN 'Thursday'THEN 'QUINTA'WHEN 'Friday'THEN 'SEXTA'WHEN 'Saturday'THEN 'SÁBADO'WHEN 'Sunday'THEN 'DOMINGO'END AS DIA_SEMANA
,CASE WHEN DATENAME(MM,[DATE]) IN ('January', 'February','March') THEN 1 WHEN DATENAME(MM,[DATE]) IN ('April', 'May','June') THEN 2 WHEN DATENAME(MM,[DATE]) IN ('July', 'August','September') THEN 3 WHEN DATENAME(MM,[DATE]) IN ('October', 'November', 'December') THEN 4 END AS TRIMESTRE
,CASE WHEN DATENAME(MM,[DATE]) IN ('January', 'February') THEN 1 WHEN DATENAME(MM,[DATE]) IN ('March', 'April') THEN 2 WHEN DATENAME(MM,[DATE]) IN ('May','June') THEN 3 WHEN DATENAME(MM,[DATE]) IN ('July', 'August') THEN 4 WHEN DATENAME(MM,[DATE]) IN ('September', 'October') THEN 5 WHEN DATENAME(MM,[DATE]) IN ('November', 'December') THEN 6 END AS BIMESTRE
,CASE WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0101  THEN 'CONFRATERNIZAÇÃO UNIVERSAL' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 2104  THEN 'TIRADENTES' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0105  THEN  'DIA DO TRABALHO' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0709  THEN 'INDEPÊNCIA DO BRASIL' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 1210  THEN  'NOSSA SENHORA APARECIDA' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 0211  THEN  'FINADOS' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 1511  THEN 'PROCLAMAÇÃO DA REPÚBLICA' WHEN REPLACE(CONVERT(CHAR(6), [DATE], 105),'-','') = 2512 THEN 'NATAL' ELSE  NULL END AS NOME_FERIADO
,FORMAT(CAST(DATEADD(DAY, -1*(DATEPART(WEEKDAY, [DATE])-2), [DATE]) AS DATE), 'dd/MM', 'pt-BR' )+' a '+FORMAT(DATEADD(DAY,7,CAST(DATEADD(DAY, -1*(DATEPART(WEEKDAY, [DATE])-2), [DATE]) AS DATE)), 'dd/MM', 'pt-BR') AS SEMANA_DE_ATE


FROM DATES_2

) AS V1

OPTION (MAXRECURSION 32767) 


SELECT 
	[SKDATA] 
,	[DATA] 
,	[DATA2] 
,	[ANO] 
,	[ANO_BISSEXTO] 
,	[ANO_MES] 
,	[MES] 
,	[DIA] 
,	[DIA_MES] 
,	[DIA_SEMANA]
,	[DIA_ANO] 
,	[DIA_UTIL] 
,	[NUMERO_DIA_SEMANA]
,	[FINAL_SEMANA] 
,	[FERIADO]
,	[NOME_FERIADO] 
,	[NOME_MES] 
,	[NOME_MES_ABREV]
,	[NOME_ANO_MES]
,	[BIMESTRE] 
,	[TRIMESTRE] 
,	[SEMESTRE] 
,	[ESTACAO]
,	[EVENTO] 
,	[SEMANA_DE_ATE]
,	[DIA_ANO_AJUSTADO]
FROM (
SELECT * FROM #TEMP_DIM_DATA_1
UNION ALL
SELECT * FROM #TEMP_DIM_DATA_2
) AS V1





END
GO


