USE [BDN]
GO

/****** Object:  StoredProcedure [dbo].[D_HORA_PROCEDURE]    Script Date: 14/10/2021 08:57:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




-- =============================================
-- Author:		<RAFAEL_BARBOSA>
-- Create date: <2021-05-19>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[D_HORA_PROCEDURE]

AS
BEGIN

IF (OBJECT_ID('tempdb.dbo.#HORA') IS NOT NULL )  BEGIN DROP TABLE #HORA	END;
IF (OBJECT_ID('tempdb.dbo.#MINUTO') IS NOT NULL) BEGIN DROP TABLE #MINUTO END;
IF (OBJECT_ID('tempdb.dbo.#SEGUNDO') IS NOT NULL) BEGIN DROP TABLE #SEGUNDO END;

;WITH HORA ([HORA]) AS(
SELECT 1 AS [HORA]
UNION ALL
SELECT  [HORA]+1
FROM HORA
WHERE [HORA] < 24)

SELECT * INTO #HORA FROM HORA

;WITH MINUTO ([MINUTO]) AS(
SELECT 1 AS [MINUTO]
UNION ALL
SELECT  [MINUTO]+1
FROM MINUTO
WHERE [MINUTO] < 60)

SELECT * INTO #MINUTO FROM MINUTO

;WITH SEGUNDO ([SEGUNDO]) AS(
SELECT 1 AS [SEGUNDO]
UNION ALL
SELECT  [SEGUNDO]+1
FROM SEGUNDO
WHERE [SEGUNDO] < 60)

SELECT * INTO #SEGUNDO FROM SEGUNDO

SELECT *
,CAST(V1.HORA_TIME AS CHAR(8)) AS HORA_STRING
,CAST(V1.HORA_INTERVALO AS CHAR(8)) AS HORA_INTERVALO_STING

FROM (  SELECT *
		,CAST(DATEADD(SECOND,S.SEGUNDO,DATEADD(MINUTE,M.MINUTO,DATEADD(HOUR, H.HORA, '1900-01-01 00:00:00'))) AS TIME(0)) AS HORA_TIME
		,CAST(DATEADD(MINUTE,IIF(M.MINUTO<30,0,30),DATEADD(HOUR, H.HORA, '1900-01-01 00:00:00')) AS TIME(0)) HORA_INTERVALO
		,IIF(H.HORA  BETWEEN 0 AND 6,'MADRUGADA', IIF(H.HORA  BETWEEN 7 AND 11,'MANHA',IIF(H.HORA  BETWEEN 12 AND 18,'TARDE','NOITE'))) AS PERIODO

		FROM #HORA AS H

		CROSS JOIN #MINUTO AS M
		CROSS JOIN #SEGUNDO AS S

) AS V1



END
GO


